"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var commander_1 = require("commander");
var hello_1 = require("./hello");
var mock_1 = require("./mock");
var program = new commander_1.Command();
program.name('ovo-cli').description('ovo cli tools').version('0.0.4');
(0, hello_1.registerHello)(program);
(0, mock_1.registerMock)(program);
program.parse(process.argv);
